<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ST10438767_PROG6221_POE_Pt1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="heinzdoofenshmirtz.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="heinzdoofenshmirtz.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="9.0.4" />
    <PackageReference Include="System.Windows.Extensions" Version="9.0.4" />
  </ItemGroup>

</Project>
